char* tabela_textos[] PROGMEM = 
{
"",        // tabela_textos[0]
"MENU 1",  // tabela_textos[1]
"MENU 2",  // tabela_textos[2]
"HORA E DATA", // tabela_textos[3]
"TESTAR LED", // tabela_textos[4]
"CONTROLE PARAM.", // tabela_textos[5]
"GRAFICOS", // tabela_textos[6]
"ALT. VALORES LED", // tabela_textos[7]
"TPA AUTOMATICA", // tabela_textos[8] // Troca Parcial de Água automática.
"DOSADORAS", // tabela_textos[9]
"WAVEMAKER", // tabela_textos[10]
"INICIO", // tabela_textos[11]
"ALTERAR HORA E DATA", // tabela_textos[12]
"SALVAR", // tabela_textos[13]
"HORA:", // tabela_textos[14]
"DATA:", // tabela_textos[15]
"TESTAR VARIACAO DE LUMINOSIDADE", // tabela_textos[16]
"INICIAR", // tabela_textos[17]
"TESTE", // tabela_textos[18]
"TESTAR VARIACAO DE LUMINOSIDADE", // tabela_textos[19]
"PARAR", // tabela_textos[20]
"TESTE EM ANDAMENTO", // tabela_textos[21]
"TEMPO:", // tabela_textos[22]
"POTENCIA DE SAIDA (0-255):", // tabela_textos[23]
"CONTROLE DE TEMPERATURA DA AGUA", // tabela_textos[24]
"GRAFICO DE TEMPERATURA", // tabela_textos[25]
"GRAFICO DE ORP", // tabela_textos[26]
"GRAFICO DE PH DO AQUARIO", // tabela_textos[27]
"GRAFICO DE PH DO REATOR DE CALCIO",// tabela_textos[28]
"GRAFICO DE DENSIDADE",// tabela_textos[29]
"ALTERAR POTENCIAS DOS LEDS BRANCOS", // tabela_textos[30]
"ALTERAR POTENCIA DOS LEDS AZUIS", // tabela_textos[31]
"CONF. DIAS E HORARIO PARA TPA AUTOMATICA",// tabela_textos[32]
"ALTERAR CONFIGURACAO DAS DOSADORAS",// tabela_textos[33]
"ESCOLHA UM GRAFICO",// tabela_textos[34]
"WAVEMAKER", // tabela_textos[35]
"ESCOLHA UM PARAMETRO", // tabela_textos[36]
"CONTROLE DE PH DO REATOR DE CALCIO", // tabela_textos[37]
"CONTROLE DE ORP", // tabela_textos[38]
"CONTROLE DE PH DO AQUARIO",// tabela_textos[39]
"CONTROLE DE DENSIDADE", // tabela_textos[40]
"ESCOLHA UMA DOSADORA", // tabela_textos[41]
"CALIBRAR DOSADORA", // tabela_textos[42]
"DOSAGEM MANUAL", // tabela_textos[43]
"CONFIGURAR DOSAGEM AUTOMATICA" ,// tabela_textos[44]
"CONFIGURAR DOSAGEM PERSONALIZADA", // tabela_textos[45]
"DIGITE A SENHA", // tabela_textos[46]
"CONFIGURAR DOSAGEM PERSONALIZADA", // tabela_textos[47]
"ALTERAR CONFIGURACAO DAS DOSADORAS", // tabela_textos[48]
"REVER CONF. DA DOSAGEM AUTOMATICA", // tabela_textos[49]
"REVER CONF. DA DOSAGEM PERSONALIZADA", // tabela_textos[50]
"DESATIVAR DOSADORAS", // tabela_textos[51]
"LUZ NOTURNA   255 = 100 %", // tabela_textos[52]
"SELECIONE O TIMER", // tabela_textos[53]
"CONFIGURAR TIMER 1", // tabela_textos[54]
"CONFIGURAR TIMER 2", // tabela_textos[55]
"CONFIGURAR TIMER 3", // tabela_textos[56]
"CONFIGURAR TIMER 4", // tabela_textos[57]
"CONFIGURAR TIMER 5", // tabela_textos[58]
"SEGUNDA", // tabela_textos[59]
"TERCA", // tabela_textos[60]
"QUARTA", // tabela_textos[61]
"QUINTA", // tabela_textos[62]
"SEXTA", // tabela_textos[63]
"SABADO", // tabela_textos[64]
"DOMINGO", // tabela_textos[65]
"VOLTAR", // tabela_textos[66]
"LUA NOVA", // tabela_textos[67]
"LUA CRESCENTE", // tabela_textos[68]
"LUA CHEIA",  // tabela_textos[69]
"S", // tabela_textos[70] // Segunda, Sexta e Sábado
"T",// tabela_textos[71]
"Q", // tabela_textos[72] // Quarta e Quinta
"D", // tabela_textos[73]
"TEMPERATURA DESEJADA:", // tabela_textos[74]
"VARIACAO PERMITIDA:", // tabela_textos[75]
"VARIACAO PARA ACIONAR O ALARME:", // tabela_textos[76]
"POTENCIA DOS LEDS BRANCOS: 255 = 100%", // tabela_textos[77]
"AZUL", // tabela_textos[78]
"POTENCIA LEDS AZUIS: 255 = 100%", // tabela_textos[79]
"BRANCO", // tabela_textos[80]
"ALTERAR", // tabela_textos[81]
"SALVAR EEPROM", // tabela_textos[82]
"HORA:", // tabela_textos[83]
"DURACAO MAXIMA", // tabela_textos[84]
"POR ESTAGIO:", // tabela_textos[85]
"FALHA!", // tabela_textos[86]
"NORMAL", // tabela_textos[87]
"MANUAL", // tabela_textos[88]
"AUTOMATICO", // tabela_textos[89]
"PERSONALIZADO", // tabela_textos[90]
"REVER CONFIG.", // tabela_textos[91]
"DESATIVAR MODOS", // tabela_textos[92]
"TEMPERATURA", // tabela_textos[93]
"PH AQUARIO", // tabela_textos[94]
"PH REATOR", // tabela_textos[95]
"ORP", // tabela_textos[96]
"DENSIDADE", // tabela_textos[97]
"CALIBRAR SONDAS", // tabela_textos[98]
"PH DESEJADO:", // tabela_textos[99]
"ORP DESEJADA:", // tabela_textos[100]
"DENSIDADE DESEJADA:", // tabela_textos[101]
"DOSADORA 1", // tabela_textos[102]
"DOSADORA 2", // tabela_textos[103]
"DOSADORA 3", // tabela_textos[104]
"COLOQUE O RECIPIENTE SOB O BICO", // tabela_textos[105]
"DOSADOR E CLIQUE EM INICIAR.", // tabela_textos[106]
"EM SEGUIDA INSIRA O VALOR OBTIDO", // tabela_textos[107]
"EM ML NO CAMPO ABAIXO.", // tabela_textos[107]
"PARA MELHORES RESULTADOS REPITA O TESTE", // tabela_textos[109]
"ALGUMAS VEZES E USE UMA MEDIA.", // tabela_textos[110]
"DOSADORA 1 SELECIONADA", // tabela_textos[111]
"DOSADORA 2 SELECIONADA",// tabela_textos[112]
"DOSADORA 3 SELECIONADA", // tabela_textos[113]
"SELECIONE O VOLUME A SER DOSADO", // tabela_textos[114]
"EM ML NO CAMPO ABAIXO  E", // tabela_textos[115]
"EM SEGUIDA TOQUE EM INICIAR.", // tabela_textos[116]
"A DOSAGEM INICIARA EM 10 SEGUNDOS",// tabela_textos[117]
"INICIAL:", // tabela_textos[118]
"FINAL:", // tabela_textos[119]
"SELECIONE O", // tabela_textos[120]
"VOLUME ", // tabela_textos[121]
"(ML/DIA):",  // tabela_textos[122]
"QUANTIDADE",  // tabela_textos[123]
"DE DOSES:",  // tabela_textos[124]
"SELECIONADA", // tabela_textos[125]
"ON", // tabela_textos[126]
"OFF", // tabela_textos[127]
"QUANTIDADE DE DOSES:", // tabela_textos[128]
"DOSADORA 1:", // tabela_textos[129]
"DOSADORA 2:", // tabela_textos[130]
"DOSADORA 3:", // tabela_textos[131]
"LUA MINGUANTE", // tabela_textos[132]
"CALIBRAR", // tabela_textos[133]
"DESATIVAR MODOS", // tabela_textos[134]
"PROXIMO", // tabela_textos[135]
"LIMPAR", // tabela_textos[136]
"ENTRAR", // tabela_textos[137]
"ANTERIOR", // tabela_textos[138]
"AUTOMATICO", // tabela_textos[139]
"PERSONALIZADO", // tabela_textos[140]
"USE ESTA", // tabela_textos[141]
"FUNCAO", // tabela_textos[142]
"APENAS PARA", // tabela_textos[143]
"DESATIVAR", // tabela_textos[144]
"OS MODOS", // tabela_textos[145]
"DE DOSAGEM.", // tabela_textos[146]
"ATIVADO", // tabela_textos[147]
"DESATIVADO", // tabela_textos[148]
"UM DOS MODOS", // tabela_textos[149]
"DE DOSAGEM ", // tabela_textos[150]
"ESTA:", // tabela_textos[151]
"DESATIVADOS", // tabela_textos[152]
"AMBOS OS MODOS", // tabela_textos[153]
"ESTAO OU", // tabela_textos[154]
"SERAO:", // tabela_textos[155]
"ILUMINACAO MINIMA:", // tabela_textos[156]
"LUA CHEIA:", // tabela_textos[157]
"LUA NOVA:", //  tabela_textos[158]
"LUZ NOTURNA", // tabela_textos[159]
"TIMERS", // tabela_textos[160]
"LIGAR TIMER", // tabela_textos[161]
"DESLIGAR TIMER", // tabela_textos[162]
"ALTERADO!", // tabela_textos[163]
"MODO MANUAL SELECIONADO", // tabela_textos[164]
"MODO AUTOMATICO SELECIONADO", // tabela_textos[165]
"INTERVALO ", // tabela_textos[166]
"ERRADO!", // tabela_textos[167]
"HORA FINAL", // tabela_textos[168]
"ERRADA!", // tabela_textos[169]
"HORA", // tabela_textos[170]
"MODO PERSONALIZADO SELECIONADO", // tabela_textos[171]
"MODO CALIBRACAO SELECIONADO",  // tabela_textos[172]
"SENHA CORRETA", // tabela_textos[173]
"SENHA INCORRETA!", // tabela_textos[174]
"MAXIMO 6 DIGITOS!", // tabela_textos[175]
"O INTERVALO ENTRE A INICIAL E A FINAL", // tabela_textos[176]
"DEVE SER DE NO MINIMO 10 MINUTOS!", // tabela_textos[177]
"A HORA FINAL NAO PODE SER MENOR", // tabela_textos[178]
"QUE A INICIAL!",// tabela_textos[179]
"ILUMINACAO MAXIMA:", // tabela_textos[180]
"% ILUMINADA", // tabela_textos[181]
"FASE LUNAR:", // tabela_textos[182]
"T.DISSIPADOR:", // tabela_textos[183]
"TEMP. AGUA:", // tabela_textos[184]
"PH DO AQUARIO:",  // tabela_textos[185]
"PH DO REATOR:",  // tabela_textos[186]
"DENSIDADE:", // tabela_textos[187]
"ORP:", // tabela_textos[188]
"CHILLER:", // tabela_textos[189]
"AQUECEDOR:", // tabela_textos[190]
"REATOR:", // tabela_textos[191]
"OZONIO:", // tabela_textos[192]
"REPOSICAO:", // tabela_textos[193]
"NIVEL:", // tabela_textos[194]
"TPA:", // tabela_textos[195]
"BAIXO!", // tabela_textos[196]
"NORMAL", // tabela_textos[197]
"Q", // tabela_textos[198] // Quinta
"S", //  tabela_textos[199] // Sexta 
"S", // tabela_textos[200] // Sábado
"CONFIG. LEDS",// tabela_textos[201]
"CONFIGURAR LEDS", // tabela_textos[202]
"SELECIONE UM PERIODO." // tabela_textos[203]
};
